## Numpy


modules and import

In [1]:
# import _____
# import _________ as  ______
# from ______ import ______


In [4]:
import math

math.sqrt(10)

3.1622776601683795

In [5]:
import math as m

m.sqrt(10)

3.1622776601683795

numpy

In [6]:
# python list are slow
# takes lot of space 


In [7]:
import numpy as np

In [24]:
# how to create numpy array
l = [1,2,3]
np.array(l)

a = np.zeros(10,int)
b = np.ones(10)
print(a)
print(a.dtype)
print(b)
print(b.dtype)

#muli-dimenstional array
c = np.ones((2,3),int)
print(c)
print(np.zeros((2,3,2),int))

a[0] ="1" #convert "1"  to 1
print(a)


[0 0 0 0 0 0 0 0 0 0]
int64
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
float64
[[1 1 1]
 [1 1 1]]
[[[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]]
[1 0 0 0 0 0 0 0 0 0]


In [26]:
c[0][2]
#slicing works as same

# we can ask for shape

print(c.shape)

(2, 3)


In [34]:
a = np.array([[1,2,3],[4,5,6],[3,6,7],[1,6,9]])
a[0]
a[:,0]
a[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [35]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
a = np.array([0, 1, 2, 3])
a.shape

(4,)

In [45]:
# numpy do element wise operation
a = np.array([1,2,3])
b = np.array([2,3,4])
c = a + b
print(c)
l = [[j for j in range(3)] for i in range(3)]
m1 = np.array(l)
l2 = [[j for j in range(3)] for i in range(3)]
m2 = np.array(l2)
print(m1 * m2)

[3 5 7]
[[0 1 4]
 [0 1 4]
 [0 1 4]]


In [49]:
print(m2.mean())
print(m2.sum())

1.0
9


In [58]:
a = np.array([1,2,3])
b = np.array([5,6,7])
d = ((a-b)**2).sum()
m.sqrt(d)


6.928203230275509

In [70]:
a = np.array([1,3,5,6])
x = a.mean()
a = ((a-x)**2)
s = a.sum()

print(s)

14.75


In [71]:
a1 = np.array([[1,2],[3,4]])
a2 = np.array([[10,20],[30,40]])
a1.dot(a2)

array([[ 70, 100],
       [150, 220]])

In [72]:
 a = np.array([5, 1, 2, 1])
 a.mean()

2.25

In [73]:
a = np.array([0, 1, 2, 3])
b = np.array([2, 3, 4, 5])
a.dot(b)

26

In [74]:
a = np.matrix('1 2 4; 3 4 5')
a.shape

(2, 3)

In [76]:
np.sum([[0, 1], [0, 5]], axis=1)

array([1, 5])