In [2]:
import numpy as np
import pandas as pd
from sklearn import model_selection

In [3]:
test_values=np.loadtxt("test.csv",delimiter=',')
#change if want to change anything in this 


#til this if any
df=pd.DataFrame(test_values)
df[4]=1
finaltest=df.values
finaltest.shape

(2392, 5)

In [4]:
#for finding the train data 

train_inputs=np.loadtxt("train.csv",delimiter=',')
#print(train_inputs)
y=train_inputs[:,train_inputs.shape[1]-1]
x=train_inputs[:,0:train_inputs.shape[1]-1]

print(x)
#print("\n************The output for training data is************ \n",y[0][0])


[[   8.58   38.38 1021.03   84.37]
 [  21.79   58.2  1017.21   66.74]
 [  16.64   48.92 1011.55   78.76]
 ...
 [  29.8    69.34 1009.36   64.74]
 [  16.37   54.3  1017.94   63.63]
 [  30.11   62.04 1010.69   47.96]]


In [5]:
#printiing the values of x and y as a trained data
#print(x,"\n",y)
#print('\n',x.shape," ",y.shape)
df=pd.DataFrame(x)
df[4]=1
x=df.values
x.shape

(7176, 5)

In [6]:
m_values=(np.zeros(x.shape[1])).reshape(-1,1)
m_values
print(df.head())
print(np.dot(x,m_values))

       0      1        2      3  4
0   8.58  38.38  1021.03  84.37  1
1  21.79  58.20  1017.21  66.74  1
2  16.64  48.92  1011.55  78.76  1
3  31.38  71.32  1009.17  60.42  1
4   9.20  40.03  1017.05  92.46  1
[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]


In [97]:
def cof(x,y,final_m):

SyntaxError: unexpected EOF while parsing (<ipython-input-97-38676495f5d2>, line 2)

In [7]:
def cost(x,y,m_values):
    total=0
    for i in range(len(x)):
        total=total+(1/len(x))*( ( y[i] - ( np.dot( x[i,:],m_values ) ).sum() )**2 )
        
    return total 

In [8]:
def gd(rate,iteration,x,y):
    m_values=(np.zeros(x.shape[1])).reshape(-1,1)
    
    for i in range(iteration):
        m_values=single_gradient(rate,m_values,x,y)
        print(i," cost is ",cost(x,y,m_values))
        
    return m_values

In [9]:
def single_gradient(rate,m_values,x,y):
    m_slope=(np.zeros(x.shape[1]).reshape(-1,1))
    m=len(x)
    
    for i in range(len(x)):
        row=x[i,:]
        for j in range(len(m_values)):
            m_slope[j]+=(-2/m)*(y[i]-np.dot(row,m_values).sum())*row[j]
    
    return m_values-rate*m_slope
    

In [10]:
def run():
    rate=.000001
    iteration=100
    final_m=gd(rate,iteration,x,y)
    
    yfinal=np.zeros(len(finaltest))
    yfinal=yfinal.reshape(-1,1)
    
    print(" the value of final m is \n", final_m)
    for i in range(len(finaltest)):
        yfinal[i]=(np.dot(finaltest[i],final_m).sum())    
        
#coefficent( x,y,final_m)

    np.savetxt("project1ans.csv",yfinal,delimiter=',',fmt='%1.5f')

In [11]:
run()

0  cost is  237116.9153476344
1  cost is  271882.1255768481
2  cost is  311750.0878720959
3  cost is  357469.76702449785
4  cost is  409900.0583638327
5  cost is  470025.9229941026
6  cost is  538976.8913048112
7  cost is  618048.2823655471
8  cost is  708725.5378320655
9  cost is  812712.1275014827
10  cost is  931961.5507511968
11  cost is  1068714.0350415877
12  cost is  1225538.6209019052
13  cost is  1405381.424008927
14  cost is  1611620.98101187
15  cost is  1848131.718831461
16  cost is  2119356.739769939
17  cost is  2430391.2897751248
18  cost is  2787078.477896192
19  cost is  3196119.045120118
20  cost is  3665197.2447092105
21  cost is  4203125.198832523
22  cost is  4820008.443378939
23  cost is  5527435.7708826605
24  cost is  6338696.937955714
25  cost is  7269032.327087479
26  cost is  8335919.252964732
27  cost is  9559400.291872669
28  cost is  10962459.802184315
29  cost is  12571455.70926189
30  cost is  14416614.666299786
31  cost is  16532599.89321231
32  cost is